{
  imports = [
    ./monitoring.nix
    ./reboot-required-check.nix
    ./maddy
    ./cockpit
    ./podman
    ./traefik
    ./nfs
    ./nix-serve
    ./glances
    ./syncthing
    ./restic
    ./adguardhome
    ./postgresql
    ./blocky
    ./code-server
    ./grafana
    ./radicale
    ./node-red
    ./nginx
    ./calibre-web
    ./rss-bridge
    ./paperless
    ./redis
    ./recyclarr
    ./sonarr
    ./radarr
    ./invidious
    ./thelounge
    ./victoriametrics
    ./readarr
    ./lidarr
    ./prowlarr
    ./mariadb
    ./code-server
    ./navidrome
    ./vikunja
    ./silverbullet
    ./tandoor
    ./vaultwarden
  ];
}
