{ config, lib, pkgs, imports, modulesPath, ... }:

with lib;
{
  # NOTE
  # Some 'global' areas have defaults set in their respective modules.
  # These will be applied when the modules are loaded
  # Not the global role.
  # Not sure at this point a good way to manage globals in one place
  # without mono-repo config.

  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-config-generate
      ./global
    ];

  config = {

    boot.tmp.cleanOnBoot = true;

    mySystem = {

      # basics for all devices
      time.timeZone = "America/New_York";
      security.increaseWheelLoginLimits = true;
      system.packages = [ pkgs.bat ];
      domain = "cassies.app";
      internalDomain = "internal.cassies.app";

      #shell.zsh.enable = true;
      shell.fish.enable = true;
      # But wont enable plugins globally, leave them for workstations
      #system.resticBackup.remote.location = "s3:https://f3b4625a2d02b0e6d1dec5a44f427191.r2.cloudflarestorage.com/nixos-restic";
    };

    environment.systemPackages = with pkgs; [
      curl
      wget
      dnsutils
      tree
      powertop
      usbutils
      parted
      smartmontools
      comma
      tailscale
    ];

    services.tailscale.enable = true;

    networking.useDHCP = lib.mkDefault true;
    networking.domain = config.mySystem.domain;

    # This being enabled stops boot on any mount failing
    # which can be a pain with the NAS
    # as it makes it harder to troubleshoot-fix
    # than just continuing as far as possible
    systemd.enableEmergencyMode=false;

    # powerManagement.powertop.enable = true;
  };

}
