---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  hostname: $HOSTNAME
  host: '{{ or .host .hostname }}'


tasks:
  test:
    desc: Build and apply nix configuration remotely
    silent: true
    requires:
      vars:
        - host
    cmds:
      - echo "This will switch your config."
      - ssh "cd ~/cassie-box && git add . && nixos-rebuild build --show-trace --flake .#cassie-box --option eval-cache false"
