system:
    services:
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:Wk4/Bx7PljIh+QA5QGs36Pvkl+XMfX9zAgLFo51xry6Mb6NhuKgf7Q==,iv:4kCA0e7wdLdagCjVW0hLDwDFZJDHixrIcib1Gke8dPQ=,tag:5K72x4p9U2Oimn6jifCLsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ekZrQ2xsNURPLytZZ2tN
            UmluYW5yQjhwcEIxTFUrdjVweUJtRkFnZDEwClBSWHdQR1ZOSHdjS3ZLWHlvMHRo
            YVRQK20xQktLYThrMzM2WmFNdWhTbzAKLS0tIHhpcVBad2dkdXlwejhEdHlIV1Ar
            Q3ZwQTZGY2JURnc5VUlYdmhDTG1vdFEK3v27XsGbxZGcTCYA+ez9HD0r9uPS+8ze
            up/W5bGNrYKJadXIJpPgyQX28AXGWpbLqZ73mRJXAGYSrG28eHIrPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYWllcXp5SlRUc3lRRmtn
            L0VBU0s4U3oyZXNlNnNMaVVEeGlMMVFqQUdrCkVYMlFwRFdSakhleXVsMkFFZUY3
            SFpXQ2gramgyYklBY2ZZRjVEVTc1aWMKLS0tIGVCWEtFL2JoT2lKYklKWW52SHFk
            d0hiZThpNHE2dHlDMmRZVmNqV2JNYncKCQ/XCOsas5o6tZgwPm6iW23wiZkG7+Ms
            0NswXjvAuVeteg4PfmwdQX0G6gcK2VwIkjiSTnSOQJoMQo4YPROMHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1lhSUFrUkRBZkg1blVU
            dWhyUzJjaEloRjNab2lpaHRmU3NHMSt4ZnowClI3K3VTRnYxUmF6REF5U1VEZURI
            bnhyWGxrVFY3MVlLdWZWSktFbDZ3czAKLS0tIFNvcDZMUHhGOXJaNXZxdVFLSmVt
            MXBHOWwwQkwvQ1VKVG1IdHpuWmlxZEEKnNCKIlNJTHIfPWw0RHQZ+IrZrLXbKmxv
            Blyo2D3ijuAgY94xnHDC7H//p9rSGx1uwvCEv4Ywx8yWZHDRI5qh+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dr2qce574ns7vcyy9q5qwml405maqd2kcp83vyxpuhyw2cquguusdekdtc
    lastmodified: "2026-09-30T18:23:22Z"
    mac: ENC[AES256_GCM,data:nwx8sVQj21VspHafHnK/3ljXBl/x1HQDbAm9IE+v5RuCumB1wl8HowVYQWibUCKo9yKzsIfpKcstpj+cKNdn+QmRRKZ/7rUWnSPAmQEYUSJdzpDxV0D40CQ7OtCX4PRkww4yO5xvKvD5rSZUqWWeKB8Bt1B0vl9eL4k5mjGazNc=,iv:FV+ondhmLJzulY0PsWftdLBfdCQ/8OGp7b3rGQCfKQo=,tag:ZLnc//1sY8Fad4+7zKFGvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
