system:
    services:
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:UacbwwQN4Pf6XiZD7ReGahhe8GngSMtL5ATDu4bZF6rxIL0hDuzePw==,iv:8fAKca8evnx9KCWbDtcgVm2JhCNGgXxPfrYvXda/FaE=,tag:wrCua3c5zFijFUeSwrkTnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVmhuM2w2dDJCUkFtQ1NN
            MDRaTmd4ZitoN2RsR2haeXE4YmVGSlNKbGtvCnpMSTc1MnpwVkRLeHpnQkRoZUpq
            aHh6bWdRUlptVkNtUW9rOHJHeStzSWMKLS0tIEVXWXd6eUxZajRXN2tLaUxjMjZB
            UGFRNG40MlBpdlZkNmJyWVYrd29uaHMKRbMRfDVi+1YhSOcGaOM5p1JsRTvTAkBx
            e6p07FAKZaU1hyvutDpznubVCgu4b+ESecN6Nd9dKrJuWjDUDqh/HQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QktNOHNJVlhTZkk3cFRj
            MUdFTTBTU2VZRTljRWhKSnZxcyszSGtkU3pJCkJUTElNOEQyMlpHdzhhelNTMzJn
            QXZVUEZIdWI0NUN6WGJpT3lYMGZ3ZEkKLS0tIFh2QmhGYUZIODE4WXlFNndadk5h
            ZWVmNFpNdVpjeFdTNEcvalBxOFNhT2MKn4LLC2uVdxQ7BHc9sewxZOjPGk42VEEJ
            AbBZx0XrQNZpv+lukyUiKRhmCQiCaLYIEIlg1ebUIreK0X0GogDKNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT3BDRWJjdjF5eC93SE9l
            RURUL0MwUU9hUEhscCtXRnNWUjlMZmp2S0FrCkRUaXdJMnZ1eWpBcHIzVTNPVDdT
            RDRxY3ExZVY1WFo5aW45MUVjRU8ydUUKLS0tIHRvdUdaZ0poMzl5NGVmcjZnWjRT
            VlYrYXJwWk8xSGlQMFl4TnBST2R4UFkKDMYsPJlCCHnIvNRVNdgoeK4+ThoEsvMy
            V1Sjig+zEuSMoVlL8qj8qmi2FnYQhfLQ3r5KNO86eWS86X9TcyZ1KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dr2qce574ns7vcyy9q5qwml405maqd2kcp83vyxpuhyw2cquguusdekdtc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRVQzVUIzMm5OUTVQUmM2
            L2xWT08zcjEyREF6dTJ6c2hVcjlWeHFzSWdJCmluMzY4OGN5VHZWNWY4WVd1eERM
            di9uVWRhS3VMT2tIRzFBbWgvRHVhQVEKLS0tIDBPN0dNc3Qwb212Q3hXZEkyUTFq
            VkhJejAyZjJQQnVrVlNmNnBGdVJkSjgK/pFRrSLo+EDh54Xehz72MouBmVeuC+am
            52aWDo2SUeszs73HKP8O6ibD+tiIfVLyxr0/QU13EEqaeGGTHjlUJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gen5vrtd8aafhujw7kxnqvjx8775nsmvzchlc8yhzc6zjmz765hq4u6pmn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYlduQjBhOTIrcEhYUFhJ
            cG5EUjRnUG5zOHJLMmduWEFFNHY3UzZOODFZCjFJcE1qdGFhTjVyRDlqb0tkUW5N
            T09UUFJqUHo5WDRDNHNFbDc1QjdQWTAKLS0tIDUwY1c4L3ByelpBeTdyZHlCS0Vr
            dDRZSkZndDRxS2NmRysyS0hZbGVwdjgKzHnLtEs9LE/yNdBSfQ0f+94jFrjPyAoW
            pz1s7gwLU++JyG2fM5tbtAgFSE8Xq6QbnwrBMk8pko6e5rJvEnfRBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189drlf0mxs3609vfsanpv4htchg4evn9kv9ywazgt89tjywu2ccq60dcr7
    lastmodified: "2026-10-05T17:59:37Z"
    mac: ENC[AES256_GCM,data:BETK5SkEYzS/JJDkpw3fzyzjEuir8uQ8wSiTK0Il9EqXy+zRW9Bg8rAt7psMPMOqsOGnXfEpq3P/HJujp1gxZIo3G8R1jvzx8owDVGgjZydEUQSTrGGygeo+D2CHist3xGOJZQPyWYpNtnMlCIGN8qORrP8t8RVwTmEOc4eJxRg=,iv:F84bJK58O9gu18zQBf/tkBoJ5xsJW0sjzLHbOltJBgo=,tag:BoKf3+KX5iWAirTEUNMVeA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
