services:
    grafana:
        secret_key: ENC[AES256_GCM,data:0TTnuVUvhVOwY13nalSgm7B/1fphpaG0DapfXGXcfzQ=,iv:BsHf5Iol0bNnOypwZ2Ot3bRpo3O9ozrAQlZhtD35BUM=,tag:e9LYnbDlFbDRDEKuNSNBXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWk5uYUVJY3I2VDJ6RkNZ
            OGJJd3BzQU9mcjNldHA3ellIeUxPdUNGL0dFCkhJckpjSmZJU2NZbTk0dTloZ2JZ
            V3ZBY1FlWnFYT2FoOUwyMXl3NUxZZUkKLS0tIFVQbW5FWUVOUnhZUFkrbjd5bWVQ
            aGhJYVpaWFJ5YTBXOUZXTnRrSXFaQ3MK9mrJ7y2JI7CmCEUEHT+G+qgPRz3HoIp/
            2yOuyIq5OF7+dsARa8tJ8sVFm7a75M+6aINmqfSxZ2y+k/fTcnIpcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WnIzZ2ordHdVQW5aeW9w
            WFkwNWRPanJ0ZFB3Z0EyeXErem1iZXlrQkVvClJ2TVJmNGE1ajVyOGtab1BxcFY3
            UURoMzlWNlduODR6TEtUQ0YvdDM5VG8KLS0tIDRzWWpaZTlhbDBIdjlSQi8yVmNC
            QzNPMUwwaXhHVFlxa3dLRnNCVjF3YWsKywnp247vNOaKvOkkxhkZger3+Eme82Du
            T5ipUVUZXW+tWL2eRz1307YlvmuOmRK47SU2KC53OiYwzetK4kI4mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWjNCSExMcFpPN2VrY0Qy
            OUcrMkZMcTVmamFpdVFHQjlFcTdWWnMwL0d3CmZOOTZaYzI0eWx4UUliRnRmRytk
            azBNNGhtN2Faa0dSQTVTcWd6RlhEZzAKLS0tIHFhL3llS3psR3dNa0NWSCtuaFp1
            OWRDanlEVklYQmp5QUJtNjVITmY1clEKcxqN64j/cms/IpbyHVgeesWOt5nD1gHM
            xlmyh3WdhoFBneMEOvV3tJAnG1rDE5ZVRtIny9v4yp4AhyB22Dud1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dr2qce574ns7vcyy9q5qwml405maqd2kcp83vyxpuhyw2cquguusdekdtc
    lastmodified: "2026-09-30T18:23:21Z"
    mac: ENC[AES256_GCM,data:8h2uW43wYE+2bVU+Gn2H9uxHtWsCBOT6NLUuRV1XF+9fe3nOFE30fuFVx3hVvlg6oyJVkppj2rOtuNuWmZbveWWueLKh4cJl06CjMXHiv9aLjhEfOn3CuGC3iyp6AiHBSVXgqPmG2fzquAS3N0q8PH2Yb4xuo8OR9qBD4ThGuek=,iv:oZCF420RQgpue/dY5xND8wILplTP34CvKMubGOKcYZU=,tag:jZ12O+ta7jpvXdDRLoAMaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
