services:
    grafana:
        secret_key: ENC[AES256_GCM,data:hvRvmZRX1SKlPmQn1iEiXHfE7FHK2o9lCIsmvBz+Jkc=,iv:6GO3fLTCEqdftxB9rXTC2a15Fidw6OHZ3Kd89Ee1k90=,tag:nwF73p5djPJpI4o/hRa8dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwczNyTmtxRkt1WjlqTGQx
            dDhpd2E0d0F3Z0ZZWEhFMTZOMVlUaENCbkNBCnQ5K3VyNXRZQ2oxRDZRY3JsbTd6
            dHZjSmZVd2tPd0JYK0NHbXZad2U4V3MKLS0tIEZxdlA2cWdaMmtHZE56WVV5UWlQ
            OWhra3RGVThMRzRweW1VZUJWMUtMZU0K5dYoUXqTdByUcR/BiNAQ0v2L28nXPjDW
            9pjvVu+WjgsZKJLUuf8R/Yf1rAd+BbwxmwBg4NwWJrL1fUjt/V7Uyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdWd1ZjFNaTliandhRE5K
            UXBBSHU1VEdGenA5NnZPanJKKzR5R0hlTXdvCnFIYWc3ZjJVbTF5bUFuVkRDREZX
            ZGp2UTFXNTl6MnFMWFNZSXBoRDdsUk0KLS0tIEVQRktiVXhMM3FxbUV5bUJzM2ps
            dXdRaE92Y1dETXJnTkNibm53TXdMNGMKfn5dd2ITYpQbqhjBauJjC/IJ0SnoS1aE
            EKG4/PzbsTJE683/zHqgWQL3Tivmd/85opFwh0nhcd8PuveBdJa4Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
    lastmodified: "2026-09-02T20:48:32Z"
    mac: ENC[AES256_GCM,data:g3mHkrMHNpQ/vJxSomHa+VnZhC5eMn/ebxpqgyN23xY++ccjqAeg4ehlSLHDjqDfprsaVt9FRahQKgqcXs+Bl+TSBLhCzzamzbAnEzebweKrZU8dCeqVzCLWUrzli3vG6xkvNI2A0MdgjNSBzbd+UvVnZ/BqfLSf7JFcHSbHSH0=,iv:7fvAg0RmcybKm5nytJ93kW9xCnrXgOYP6qPxjv+y4o8=,tag:JBLUL0PNbr2DqG5w7/R8lA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
