services:
    grafana:
        secret_key: ENC[AES256_GCM,data:ADeaZvgS1aM8zV0vuUR7we6ajHrnIVTlSOK8qr9zyQo=,iv:c5nub5Un0iPTgA98EXs8gwngc46I+kJ1pyCwh/BlbZk=,tag:RTI/peTOFzCxNtvp2fdXag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZnozT0V4VkgwV2YzclNS
            Rm5MTllnRlVSTE9ibTJZbEphdy9CZjl4UWlrClh6THdTZklNdjJBRGVVVnE5RDRE
            TmFLYTRydE9GMXR1UTIvM1VOdC82eVEKLS0tIERhZTRBWExZNm1hMDlGZ1M3eTk5
            M0VyUTNKRjMyTjV0NmZQT05PVjd2SzAKy7VBfPK8Rvd2ajC+SYCebx/i0WMO5+vq
            7rwjvcsMmUqeocFL1ZdN75oAc5brAYRFsxwB9IrYd3a/rYtSRV/k/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age123dsa4ane5583sezln90h5ax8hjyx4c2r5psu6ydxy8k5xtfva6sme6pa0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFQyOUVqZGdQNE5RY2VM
            TGlJMnJ2SmgyMjlMZjlHR1hTK1NJUTluYUVFClVQVFlWRlpwZjVWVW03WUpiQnli
            d0VJWmpJT2FSS1Q1SUtHbnJDZjNoa1kKLS0tIFliNGFnaFQ0MjFMV1N5NkhmM0d1
            ZlpUODROaCtNZWI1ZnQrVUx4NGtIckEKXU+6b4Pi8AwAFrwK4dAFYMku8NJ8qibJ
            6ZUJj22/aPVb6RcOZwik+wxhp8qc5cdLZsdqZwg1kxzamJjKQrMPMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lzhjalfd2vw8xva4va459ey4389wdjh59cwn8rvlf0txagvw6f2qdpt6wp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZGJxVm1mZnArcmNiWHF4
            bHY0NW9zc1gxK3VtQjNKcFh1VnFpbUVtenhrCkswTWFkbElsa0pTemxrLzVCREhR
            K0JYMVBSbHg3bGtacGlLYXJheFY0cUEKLS0tIGpCMWRJR25KZjdJMWM4VkZEMGVa
            RGorN1Q0RWxXZWVRdW81aUtzTTVwT28KlaTEvMbNuOwOBE+Q+UIpfTjIcS6rg7fS
            KJjf4oByte3A2PDcmyPi41sGYzDa/7pd1vRuJsqK0sxnnBoIoiHpOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dr2qce574ns7vcyy9q5qwml405maqd2kcp83vyxpuhyw2cquguusdekdtc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcUYxbFRVOEs0VUVYYmgv
            TFk0Qk9tZlRsQmdEQSs5SUdlUHYzd0IrYXpzCjVEVWZWb1NhSWtTSXNCZWQyRFAv
            TWJDRFh2WUJoTGJ4ZGExWTZTd3JaZDgKLS0tIHpPLytjcXhlUU9JTVBHVFpGamxp
            Mks3dUkxdWtMWUo2cXdQL09hSzNPUjAKZlq3Z03X/3/BqXwujQmj/7qltIsGCp7f
            qov5lQMo5edXyDbHZldxCQB7ulhX/PmqWX/82BiFhovY6qxJe5wppg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gen5vrtd8aafhujw7kxnqvjx8775nsmvzchlc8yhzc6zjmz765hq4u6pmn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS0lCUGFDVVdWTURTbVRk
            OFg4aGZvaFE1eDZFUW5wb0xiYnFka1lOeUdrCmhTemYwU2ZkOEllRUJWcHNJYmhD
            WkF4WEM4VE40VE5IYVN6bWxuMFZGaHcKLS0tIDJFWFpoMDZtc0VRSExIOWRRajla
            Z0JrclhCRS9nMVJMWjcydkdoYmYySE0KeTq9O/Dg9QzGoJZ/2cBtOOFKZTj/Km47
            vrgMQ5oAk7dQGuatpCS+w/bp8GbCbuw9xbufh6swd+N8W4ClLIGwLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189drlf0mxs3609vfsanpv4htchg4evn9kv9ywazgt89tjywu2ccq60dcr7
    lastmodified: "2026-10-05T17:59:36Z"
    mac: ENC[AES256_GCM,data:LyeTICosDyTTL88uQXnHUGFUMYtHM9pXKNnZHY+vhmUzLgyjzYVmqsvqPoUfEWsSLszqclfIaSs8QjXyHRZ8op66Z44v7bd+ednaNUnwh4IyPf32BWkdFgg1C4Z6qqubOQq4RpUMAqtth/0IxHIYjTL2ULMXdj/HouGOmWXFKz8=,iv:OXHv1Wg88JEdcZ4cXzEkqG0RlEujYDzDSAu5e94LXEk=,tag:UZyDFt5Rseo7FzN1EP7SXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
